services:
  db:
    image: postgres:16
    container_name: progresspoint_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: progresspoint_app
    volumes:
      - progresspoint_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5


  # to seed the database run: npm run prisma:seed
  db-test:
    image: postgres:16
    container_name: progresspoint_db_test
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: progresspoint_app_test
    volumes:
      - progresspoint_data_test:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: .
    container_name: progresspoint_back
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://admin:secret@db:5432/progresspoint_app"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma generate && npx prisma db push --accept-data-loss && npm run prisma:seed && npm run dev"

volumes:
  progresspoint_data:
  progresspoint_data_test: